#!/bin/sh

if [ -z "${WORKDIR}" ] ; 
then 
  WORKDIR=/app
fi

echo "Updating rules ..."

curl https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt -o $WORKDIR/china-ip-list.txt
curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt -o $WORKDIR/reject-list.txt
curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt -o $WORKDIR/direct-list.txt
curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt -o $WORKDIR/proxy-list.txt
curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt -o $WORKDIR/gfw.txt
curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt -o $WORKDIR/apple-cn.txt